name: onsemiro
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.3

flutter:
  assets:
    - assets/Ralo.png
    - assets/보호자.png
    - assets/치매.png
    - assets/온새미로.png
    - assets/온새미로노랑.png
    - assets/온새미로고.png
    - assets/Frame 198.png
    - assets/Frame 201.png
    - assets/Frame 202.png
    - assets/Frame 203.png
    - assets/Frame 204.png
    - assets/Frame 205.png
    - assets/Frame 206.png
    - assets/지도.png
    - assets/회상.png
    - assets/보호.png
    - assets/Frame 215.png
    - assets/Frame 216.png
    - assets/Frame 217.png
    - assets/image 2.png
    - assets/절반.png
    - assets/색.png
    - assets/단풍.jpg
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
